"""init

Revision ID: 03924cd1d08d
Revises: 038a22f6d7e9
Create Date: 2024-04-08 19:41:25.864809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '03924cd1d08d'
down_revision: Union[str, None] = '038a22f6d7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Config',
    sa.Column('ssid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serverURL', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Config_id'), 'Config', ['id'], unique=False)
    op.alter_column('JournalDAS', 'DAS_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('JournalDAS', 'DAS_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_Config_id'), table_name='Config')
    op.drop_table('Config')
    # ### end Alembic commands ###
