"""init

Revision ID: 2ffa2785ade7
Revises: 942c5a8d40be
Create Date: 2024-03-28 14:07:15.896433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ffa2785ade7'
down_revision: Union[str, None] = '942c5a8d40be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DataAcquisitionSystem', sa.Column('hardware_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DataAcquisitionSystem', 'hardware_id')
    # ### end Alembic commands ###
