"""init

Revision ID: b439a83264c9
Revises: 03924cd1d08d
Create Date: 2024-04-08 20:05:02.937387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b439a83264c9'
down_revision: Union[str, None] = '03924cd1d08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DataAcquisitionSystem', sa.Column('config_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'DataAcquisitionSystem', 'Config', ['config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DataAcquisitionSystem', type_='foreignkey')
    op.drop_column('DataAcquisitionSystem', 'config_id')
    # ### end Alembic commands ###
